# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  save_hello_world_output:
    #output to file called output.txt
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            -output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach workspace:
          at: ~/
      - run: cat ~/output.txt

workflows:
  # Name the workflow "test-workspace"
  test-workspace:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
