# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  learn_commands:
    #output to file called output.txt
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id

workflows:
  # Name the workflow "test-workspace"
  test-commands:
    jobs:
      - learn_commands